name: libra

channels:
    - astropy

dependencies:
    - python=3.4
    - astropy=2.0
    - scipy
    - matplotlib
    - numpy
    - h5py
    - hdf5
    - pip:
        - sphinx-automodapi
        - numpydoc
        - batman-package